<?php
require_once "FormCreationBase.php";


class FormSingleCheckbox extends FormCreationBase
{
    private $formFirst = true;

    public function __construct($name = "", $isRequired = false)
    {
        parent::__construct($name, "input");
        $this->setIsRequired($isRequired);
        $this->setType("checkbox");
        $this->setClass("col-1");
    }

    public function setFormFirst($formFirst = true) {
        $this->formFirst = $formFirst;
    }

    public function setIsChecked($isChecked = true)
    {
        return parent::setIsChecked($isChecked); // TODO: Change the autogenerated stub
    }

    public function build()
    {
        return parent::build()->setFormFirst($this->formFirst); // TODO: Change the autogenerated stub
    }

}